---
title: cloudtrail-ei

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md', '/CONTRIBUTING.md']

permalink: pretty

collections:
  apilist:
    output: true

defaults:
  - scope:
      path: '_apilist'
    values:
      layout: api
